version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aeroreserve-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - aeroreserve-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: aeroreserve-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - aeroreserve-network

  backup-service:
    image: postgres:15
    container_name: backup-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    volumes:
      - ./backups:/backups
      - ./backup-scripts:/backup-scripts
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=aeroreserve_db
      - DB_USER=aeroreserve_user
      - DB_PASS=password
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET=backups
    networks:
      - aeroreserve-network
    command: >
      sh -c "
        apt-get update && 
        apt-get install -y curl wget && 
        # Устанавливаем MinIO Client
        wget -q -O /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc &&
        chmod +x /usr/local/bin/mc &&
        # Настраиваем MinIO alias
        mc alias set myminio http://minio:9000 minioadmin minioadmin123 &&
        echo '✅ Backup service with mc client ready' && 
        tail -f /dev/null
      "

volumes:
  postgres_data:
  minio_data:

networks:
  aeroreserve-network:
    driver: bridge