FROM amazon/aws-cli:latest

# Устанавливаем PostgreSQL client и необходимые утилиты
RUN yum update -y && \
    yum install -y \
    postgresql \
    gzip \
    && yum clean all

# Копируем скрипты
COPY backup-scripts/ /backup-scripts/
RUN chmod +x /backup-scripts/*.sh

CMD ["sh", "-c", "\
  aws configure set aws_access_key_id ${MINIO_ACCESS_KEY} && \
  aws configure set aws_secret_access_key ${MINIO_SECRET_KEY} && \
  aws configure set default.region us-east-1 && \
  aws configure set default.s3.endpoint_url http://${MINIO_ENDPOINT} && \
  aws configure set default.s3.signature_version s3v4 && \
  aws s3 mb s3://${MINIO_BUCKET} --endpoint-url http://${MINIO_ENDPOINT} || true && \
  echo '✅ Backup service ready' && \
  tail -f /dev/null"]