version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aeroreserve-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aeroreserve-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aeroreserve_user -d aeroreserve_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  aeroreserve-network:
    driver: bridge